FROM node:16-alpine as builder

# Create node_modules folder
RUN mkdir -p /usr/app/node_modules
# Working directory
WORKDIR /usr/app
# Copy package*.json files
COPY ./package*.json ./
# Install all dependencies
RUN npm ci
# Copy all local files to working directory
COPY . .
# Build the app
RUN npm run build

FROM nginx
# Expose port 3000
EXPOSE 3000
COPY ./.nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/app/build /usr/share/nginx/html